import type { Config } from "tailwindcss";
export default {
  darkMode: ["class"],
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
    extend: {
      fontFamily: {
        serif: ["var(--font-serif)", "Georgia", "serif"],
        sans: ["var(--font-body)", "system-ui", "sans-serif"],
        body: ["var(--font-body)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "monospace"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        night: "hsl(var(--av-night))",
        ink: "hsl(var(--av-ink))",
        gold: {
          DEFAULT: "hsl(var(--av-gold))",
          soft: "hsl(var(--av-gold-soft))",
        },
        parchment: "hsl(var(--av-parchment))",
        cream: "hsl(var(--av-parchment))",
        stone: "hsl(var(--av-stone))",
        sage: { DEFAULT: "hsl(var(--av-sage))", 500: "hsl(var(--av-sage))" },
        brand: {
          50: "hsl(var(--av-parchment))",
          100: "hsl(40 30% 92%)",
          300: "hsl(var(--av-gold-soft))",
          400: "hsl(var(--av-gold))",
          500: "hsl(var(--av-night))",
          600: "hsl(var(--av-ink))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 4px)",
        sm: "calc(var(--radius) - 8px)",
      },
      keyframes: {
        "fade-in": { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        "slide-up": { "0%": { transform: "translateY(20px)", opacity: "0" }, "100%": { transform: "translateY(0)", opacity: "1" } },
        "slow-zoom": { "0%": { transform: "scale(1)" }, "100%": { transform: "scale(1.1)" } },
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "pulse-glow": { "0%, 100%": { boxShadow: "0 0 20px rgba(201, 168, 76, 0.4)" }, "50%": { boxShadow: "0 0 40px rgba(201, 168, 76, 0.8)" } },
        "breath-scale": { "0%": { transform: "scale(0.5)", opacity: "0.1" }, "50%": { transform: "scale(1)", opacity: "0.5" }, "100%": { transform: "scale(0.5)", opacity: "0.1" } },
        "star-twinkle": { "0%, 100%": { opacity: "0.3" }, "50%": { opacity: "1" } },
      },
      animation: {
        "fade-in": "fade-in 1s ease-out forwards",
        "slide-up": "slide-up 0.8s ease-out forwards",
        "slow-zoom": "slow-zoom 20s linear infinite alternate",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "pulse-glow": "pulse-glow 3s ease-in-out infinite",
        "breath-scale": "breath-scale 8s ease-in-out infinite",
        "star-twinkle": "star-twinkle 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
