import type { CardItem } from '../../card-draw/types'

export interface TarotCardMeta {
  keywords: string
  reflection: string
  affirmation: string
  symbol: string
}

export type TarotCardItem = CardItem & TarotCardMeta

export const TAROT_CARDS: TarotCardItem[] = [
  {
    id: 'fool',
    label: 'The Fool',
    name: 'The Fool',
    theme: 'awakening',
    symbol: '🌅',
    keywords: 'Beginnings, innocence, spontaneity, free spirit',
    description: 'A fresh start. A leap of faith. The beginning of a journey.',
    reflection: 'The Fool appears when you are standing at the edge of a new beginning — and your heart knows before your mind does. This is not naivety. This is courage dressed as innocence. Something new is asking you to trust the unknown and take the first step, even if you cannot see where the path leads. The universe rewards the leap.',
    affirmation: 'I trust the unknown. My journey begins with a single brave step, and I am ready.',
  },
  {
    id: 'magician',
    label: 'The Magician',
    name: 'The Magician',
    theme: 'power_will',
    symbol: '🪄',
    keywords: 'Manifestation, resourcefulness, power, skill',
    description: 'You have everything you need. Channel your will.',
    reflection: 'The Magician appears when you have all the tools at your disposal but have forgotten your own power. You are more capable than you give yourself credit for. The universe is asking you to stop waiting for permission and start creating. Your intention, focused like a beam, can shape reality.',
    affirmation: 'I have everything I need within me. I channel my power with intention and create my reality.',
  },
  {
    id: 'high_priestess',
    label: 'The High Priestess',
    name: 'The High Priestess',
    theme: 'inner_work',
    symbol: '🌙',
    keywords: 'Intuition, mystery, the subconscious, inner knowing',
    description: 'The answers are within. Listen to your inner voice.',
    reflection: 'The High Priestess appears when logic has taken you as far as it can. She stands at the threshold of the subconscious, inviting you to trust what you know but cannot prove. Your dreams, your gut feelings, your quietest inner voice — these are speaking the truth. Stop searching outside. The answer is already within you.',
    affirmation: 'I trust my inner knowing. The answers I seek live within me, and I am patient enough to listen.',
  },
  {
    id: 'empress',
    label: 'The Empress',
    name: 'The Empress',
    theme: 'love_relationships',
    symbol: '👑',
    keywords: 'Femininity, abundance, nurture, nature',
    description: 'You are worthy of abundance. Receive without guilt.',
    reflection: 'The Empress appears when you need to remember that you are worthy of receiving — not just giving. She is the energy of unconditional love, creative fertility, and sensual abundance. If you have been running on empty, she asks you to root yourself in pleasure, beauty, and self-care. You do not have to earn love. You are love.',
    affirmation: 'I am worthy of receiving abundance. I nurture myself as tenderly as I nurture others.',
  },
  {
    id: 'emperor',
    label: 'The Emperor',
    name: 'The Emperor',
    theme: 'power_will',
    symbol: '🏛️',
    keywords: 'Authority, structure, stability, discipline',
    description: 'Build your foundation. Lead with wisdom.',
    reflection: 'The Emperor appears when you need to bring order to chaos. He is the energy of structure, boundaries, and grounded authority. If you have been feeling scattered or powerless, he asks you to step into your own leadership. Create the container for your life. Set the boundaries that protect your peace. You are the author of your own stability.',
    affirmation: 'I claim my authority. I build my life on a foundation of structure, discipline, and self-respect.',
  },
  {
    id: 'hierophant',
    label: 'The Hierophant',
    name: 'The Hierophant',
    theme: 'love_relationships',
    symbol: '📜',
    keywords: 'Tradition, wisdom, spiritual guidance, conformity',
    description: 'Seek wisdom from those who walked before you.',
    reflection: 'The Hierophant appears when you are seeking deeper meaning and structure in your beliefs. He represents the wisdom of tradition, the value of mentorship, and the power of shared knowledge. If you have been trying to figure it all out alone, he asks you to find your teachers, your community, your sacred practices. Some truths are passed down, not discovered.',
    affirmation: 'I honour the wisdom of those who came before me. I seek guidance and share my learning.',
  },
  {
    id: 'lovers',
    label: 'The Lovers',
    name: 'The Lovers',
    theme: 'love_relationships',
    symbol: '💞',
    keywords: 'Love, harmony, values alignment, choice',
    description: 'A choice of the heart. Align with your truth.',
    reflection: 'The Lovers appear when you face a choice that your heart cannot ignore. This is not just about romantic love — it is about aligning your actions with your deepest values. The card asks you to choose authenticity over comfort, truth over approval. When you honour what you truly value, the universe rearranges itself to support you.',
    affirmation: 'I choose in alignment with my truth. My heart knows the way, and I honour its wisdom.',
  },
  {
    id: 'chariot',
    label: 'The Chariot',
    name: 'The Chariot',
    theme: 'power_will',
    symbol: '⚡',
    keywords: 'Willpower, determination, victory, control',
    description: 'You are being called to rise. You have the strength.',
    reflection: 'The Chariot appears when you are being called to move forward with determination and focus. It is the card of willpower overcoming obstacles. If you have been feeling pulled in different directions, the Chariot asks you to align your conflicting desires and charge ahead. Victory belongs to those who refuse to give up.',
    affirmation: 'I am focused and determined. I move forward with strength, overcoming every obstacle in my path.',
  },
  {
    id: 'strength',
    label: 'Strength',
    name: 'Strength',
    theme: 'power_will',
    symbol: '🦁',
    keywords: 'Courage, inner strength, patience, compassion',
    description: 'True strength is gentle. Lead with your heart.',
    reflection: 'Strength appears when you need courage — not the loud kind, but the quiet kind that keeps going when everything is hard. It is the card of inner resilience, patience, and the power of gentle persistence. You are stronger than you know, but your strength is not in force. It is in your ability to stay soft in a world that hardens you.',
    affirmation: 'I am strong enough to be gentle. My courage is quiet, steady, and unwavering.',
  },
  {
    id: 'hermit',
    label: 'The Hermit',
    name: 'The Hermit',
    theme: 'inner_work',
    symbol: '🏮',
    keywords: 'Soul-searching, introspection, solitude, guidance',
    description: 'Step back. Reflect. The light you seek is within.',
    reflection: 'The Hermit appears when it is time to withdraw from the noise and turn inward. This is not loneliness — it is sacred solitude. You have been seeking answers in the external world, but the Hermit asks you to light your own lantern and look within. The answers you find in silence will be the ones that truly guide you forward.',
    affirmation: 'I honour my need for solitude. In stillness, I find the clarity I have been seeking.',
  },
  {
    id: 'wheel_of_fortune',
    label: 'Wheel of Fortune',
    name: 'Wheel of Fortune',
    theme: 'transformation',
    symbol: '🎡',
    keywords: 'Change, cycles, fate, turning point',
    description: 'Change is coming. Trust the turning of the wheel.',
    reflection: 'The Wheel of Fortune appears when a turning point is upon you. Life moves in cycles, and you are entering a new phase. What has been down will come up. What has felt stuck will begin to move. The Wheel asks you to release your grip on how things "should" be and trust the natural rhythm of life. Every end is a new beginning.',
    affirmation: 'I trust the cycles of life. Change is not loss — it is the universe making way for what is meant for me.',
  },
  {
    id: 'justice',
    label: 'Justice',
    name: 'Justice',
    theme: 'surrender',
    symbol: '⚖️',
    keywords: 'Fairness, truth, cause and effect, accountability',
    description: 'The truth will surface. Trust the process.',
    reflection: 'Justice appears when the scales are being balanced. It is the card of truth, accountability, and the natural consequences of your choices. If you have been dishonest with yourself or others, the truth will come to light. If you have been wronged, fairness will be restored. Justice asks you to take responsibility for your actions and trust that the universe is fair.',
    affirmation: 'I stand in my truth. I take responsibility for my actions and trust that balance will be restored.',
  },
  {
    id: 'hanged_man',
    label: 'The Hanged Man',
    name: 'The Hanged Man',
    theme: 'inner_work',
    symbol: '🔄',
    keywords: 'Surrender, new perspective, pause, release',
    description: 'Stop struggling. A new view is waiting.',
    reflection: 'The Hanged Man appears when the only way forward is to stop. Pause. Surrender. You have been struggling, pushing, trying to force an outcome — and it is exhausting you. The Hanged Man asks you to see the situation from a completely different angle. What if you let go? What if you stopped trying to control the outcome? Liberation is waiting on the other side of release.',
    affirmation: 'I release my need to control. I surrender to the flow, knowing that a new perspective is waiting.',
  },
  {
    id: 'death',
    label: 'Death',
    name: 'Death',
    theme: 'transformation',
    symbol: '💀',
    keywords: 'Endings, transformation, release, transition',
    description: 'One chapter ends so another can begin.',
    reflection: 'Death appears not as an ending but as a profound transformation. Something in your life is dying — a relationship, a career, an identity, a belief that no longer serves you. It is natural to grieve, but do not mistake this for punishment. Death clears the ground for what wants to grow. Let go. What is meant for you will not pass you by.',
    affirmation: 'I release what no longer serves me. I trust that every ending makes space for a truer beginning.',
  },
  {
    id: 'temperance',
    label: 'Temperance',
    name: 'Temperance',
    theme: 'surrender',
    symbol: '⚗️',
    keywords: 'Balance, moderation, patience, blending',
    description: 'Find the middle path. Patience brings harmony.',
    reflection: 'Temperance appears when you are being called to find balance. Not the balance of perfection, but the dynamic balance of constant, gentle adjustment. You have been living in extremes — all work or all rest, all giving or all withdrawing. Temperance asks you to find the middle path, to blend opposing forces with patience and grace. Slow down. You will get there.',
    affirmation: 'I find balance in all things. I move through life with patience, grace, and gentle moderation.',
  },
  {
    id: 'devil',
    label: 'The Devil',
    name: 'The Devil',
    theme: 'surrender',
    symbol: '⛓️',
    keywords: 'Attachment, addiction, materialism, shadow self',
    description: 'Name what holds you captive. Freedom begins.',
    reflection: 'The Devil appears when something is holding you captive — an addiction, a toxic pattern, a fear, a belief that you are not enough. The chains are real, but they are also self-imposed. The Devil does not keep you imprisoned; you keep yourself imprisoned by ignoring your shadow. The first step to freedom is naming what binds you. You have the key.',
    affirmation: 'I face my shadows with courage. I name what binds me, and I claim my freedom.',
  },
  {
    id: 'tower',
    label: 'The Tower',
    name: 'The Tower',
    theme: 'transformation',
    symbol: '🗼',
    keywords: 'Sudden change, upheaval, revelation, awakening',
    description: 'What was built on false ground must fall.',
    reflection: 'The Tower appears when a sudden, shocking change shatters the structures you thought were stable. This can feel devastating — a breakup, a job loss, a health crisis, a truth you cannot unsee. But the Tower is not punishment. It is a necessary demolition. What was built on false ground was never going to hold. From the rubble, you can build something real.',
    affirmation: 'When my world shakes, I stay grounded. I trust that destruction is the first step of true creation.',
  },
  {
    id: 'star',
    label: 'The Star',
    name: 'The Star',
    theme: 'awakening',
    symbol: '⭐',
    keywords: 'Hope, inspiration, renewal, serenity',
    description: 'After the storm, the stars appear. Hope is returning.',
    reflection: 'The Star appears after a period of darkness, bringing hope, healing, and a sense of renewed purpose. You have been through the fire, and you are emerging — not unscathed, but wiser and more beautiful for what you have survived. The Star asks you to open your heart to possibility again. Let yourself dream. The universe is listening.',
    affirmation: 'I am open to hope. I trust that healing is underway, and my light is returning.',
  },
  {
    id: 'moon',
    label: 'The Moon',
    name: 'The Moon',
    theme: 'inner_work',
    symbol: '🌑',
    keywords: 'Illusion, fear, anxiety, the unconscious',
    description: 'Not everything is as it seems. Trust your inner sight.',
    reflection: 'The Moon appears when things are not as they seem. Uncertainty, illusion, and hidden truths surround you. Fear may be distorting your perception, making shadows look like monsters. The Moon asks you to navigate this uncertainty not with more analysis, but with deepened intuition. You cannot see the full picture yet — and that is okay. Trust that clarity will come.',
    affirmation: 'I trust my intuition even when the path is unclear. I move through uncertainty with faith.',
  },
  {
    id: 'sun',
    label: 'The Sun',
    name: 'The Sun',
    theme: 'awakening',
    symbol: '☀️',
    keywords: 'Joy, success, vitality, positivity',
    description: 'You are stepping into your light.',
    reflection: 'The Sun appears when joy, success, and vitality are flowing freely. After difficulty comes this moment of pure, unapologetic brightness. The Sun is the card of achievement, confidence, and the simple pleasure of being alive. It asks you to step fully into your light, to celebrate how far you have come, and to share your warmth with the world.',
    affirmation: 'I step into my light. I celebrate my journey and share my joy freely with the world.',
  },
  {
    id: 'judgement',
    label: 'Judgement',
    name: 'Judgement',
    theme: 'transformation',
    symbol: '📯',
    keywords: 'Rebirth, inner calling, absolution, reflection',
    description: 'You are being called to rise. Answer the call.',
    reflection: 'Judgement appears when you are being called to rise to your next level of being. It is the card of reckoning, of hearing your inner calling, of being asked to account for how you have lived. This is not about external judgement — it is about self-evaluation. Are you living your truth? If not, Judgement asks you to answer the call now. There is no more time to wait.',
    affirmation: 'I answer the call of my soul. I rise to my next level of being and live my truth fully.',
  },
  {
    id: 'world',
    label: 'The World',
    name: 'The World',
    theme: 'awakening',
    symbol: '🌍',
    keywords: 'Completion, accomplishment, wholeness, travel',
    description: 'A cycle completes. You have arrived.',
    reflection: 'The World appears when a major life cycle is complete. You have done the work, learned the lessons, and grown through the challenges. The World is the card of fulfillment, integration, and wholeness. It asks you to pause and acknowledge how far you have come. Celebrate this completion. And then — because every ending is a beginning — prepare for the next grand adventure.',
    affirmation: 'I honour my journey. I have completed this cycle, and I am whole. I am ready for what comes next.',
  },
]
